services:
  gateway:
    build:
      context: ./gateway # Đường dẫn tương ứng với thư mục gateway trong ảnh
    container_name: cab_gateway
    ports:
      - "${GATEWAY_PORT}:3000" # Giả sử gateway chạy port 3000
    depends_on:
      - auth-service
      - user-service
      - booking-service
      - driver-service
      - ride-service
      - pricing-service
      - payment-service
      - notification-service
      - review-service
    environment:
      - JWT_SECRET=${JWT_SECRET:-supersecret}

  # --- 1. INFRASTRUCTURE ---
  postgres:
    image: postgres:16.11-alpine3.23
    container_name: cab_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cab-system-backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mongodb:
    image: mongo:8.2.5
    container_name: cab_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine3.22
    container_name: cab_redis
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  rabbitmq:
    image: rabbitmq:4.2.2-management-alpine
    container_name: cab_rabbitmq
    ports:
      - "${RABBITMQ_PORT_NODE}:5672"
      - "${RABBITMQ_PORT_UI}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: cab_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: cab_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- 2. MICROSERVICES ---
  auth-service:
    build:
      context: cab-system-backend/services/auth-service
      target: development
      args:
        - PORT=${AUTH_PORT}
    container_name: cab_auth
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      - PORT=${AUTH_PORT}
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/auth_db
      - JWT_SECRET=${JWT_SECRET:-supersecret}
      - JWT_REFRESH_SECRET=${JWT_SECRET:-supersecret}
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  booking-service:
    build:
      context: ./cab-system-backend/services/booking-service
      dockerfile: Dockerfile
    container_name: cab_booking
    ports:
      - "${BOOKING_PORT:-3002}:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - MONGODB_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-password123}@mongodb:27017
      - MONGODB_DB_NAME=booking_db
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-admin}:${RABBITMQ_PASS:-password123}@rabbitmq:5672
      - PRICING_SERVICE_URL=http://cab_pricing:${PRICING_PORT:-3006}
      - JWT_SECRET=${JWT_SECRET:-supersecret}
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  driver-service:
    build:
      context: cab-system-backend/services/driver-service
      target: development
      args:
        - PORT=${DRIVER_PORT}
    container_name: cab_driver
    ports:
      - "${DRIVER_PORT}:${DRIVER_PORT}"
    environment:
      - PORT=${DRIVER_PORT}
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/driver_db
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/driver_db?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres

  notification-service:
    build:
      context: cab-system-backend/services/notification-service
      target: development
    container_name: cab_notification
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DB_URL=mongodb+srv://hle26625_db_user:aEuxe83lA4lX9OEk@notification.jrxenun.mongodb.net/?appName=Notification
      - RABBITMQ_URL=amqp://admin:password123@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rabbitmq
      - redis

  payment-service:
    build:
      context: cab-system-backend/services/payment-service
      target: development
      args:
        - PORT=${PAYMENT_PORT}
    container_name: cab_payment
    ports:
      - "${PAYMENT_PORT}:${PAYMENT_PORT}"
    environment:
      - PORT=${PAYMENT_PORT}
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/payment_db
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  pricing-service:
    build:
      context: cab-system-backend/services/pricing-service
      target: development
      args:
        - PORT=${PRICING_PORT}
    container_name: cab_pricing
    ports:
      - "${PRICING_PORT}:${PRICING_PORT}"
    environment:
      - PORT=${PRICING_PORT}
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/pricing_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

  review-service:
    build:
      context: cab-system-backend/services/review-service
      target: development
      args:
        - PORT=${REVIEW_PORT}
    container_name: rb_preview
    ports:
      - "${REVIEW_PORT}:${REVIEW_PORT}"
    environment:
      - PORT=${REVIEW_PORT}
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/review_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  ride-service:
    build:
      context: cab-system-backend/services/ride-service
      target: development
      args:
        - PORT=${RIDE_PORT}
    container_name: cab_ride
    ports:
      - "${RIDE_PORT}:${RIDE_PORT}"
    environment:
      - PORT=${RIDE_PORT}
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/ride_db
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - kafka
      - redis

  user-service:
    build:
      context: cab-system-backend/services/user-service
      target: development
      args:
        - PORT=${USER_PORT}
    container_name: cab_user
    ports:
      - "${USER_PORT}:${USER_PORT}"
    environment:
      - PORT=${USER_PORT}
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/user_db
    depends_on:
      - postgres
    volumes:
      - ./cab-system-backend/services/user-service:/app
      - /app/node_modules

  matching-service:
    build:
      context: cab-system-backend/services/matching-service
      target: development
    container_name: cab_matching
    ports:
      - "${MATCHING_PORT:-3010}:${MATCHING_PORT:-3010}"
    environment:
      - PORT=${MATCHING_PORT}
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=matching_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DRIVER_SERVICE_URL=http://cab_driver:${DRIVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - LOG_LEVEL=info
    depends_on:
      - postgres
      - redis
      - driver-service
    volumes:
      - ./cab-system-backend/services/matching-service:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data:
