// src/middleware/idempotency.js
const { v4: uuidv4 } = require('uuid');
const crypto = require('crypto');

// Lưu trữ tạm (nên dùng Redis trong production)
const idempotencyStore = new Map();

// Hàm tạo fingerprint từ request (để tự động detect duplicate)
function generateRequestFingerprint(req) {
  const components = [
    req.method,
    req.originalUrl || req.url,
    JSON.stringify(req.body),
    req.headers['x-user-id'] || 'anonymous'
  ];
  
  return crypto
    .createHash('sha256')
    .update(components.join('|'))
    .digest('hex');
}

const idempotencyMiddleware = async (req, res, next) => {
  // Chỉ áp dụng cho POST, PUT, PATCH
  if (!['POST', 'PUT', 'PATCH'].includes(req.method)) {
    return next();
  }

  let idempotencyKey = req.headers['idempotency-key'];
  let isAutoGenerated = false;
  
  // Nếu không có key, tự động tạo từ fingerprint
  if (!idempotencyKey) {
    const fingerprint = generateRequestFingerprint(req);
    
    // Kiểm tra xem có request giống hệt nào đang xử lý không
    const existingRequest = idempotencyStore.get(fingerprint);
    
    if (existingRequest) {
      // Nếu request đang được xử lý (chưa có response), đợi kết quả
      if (existingRequest.status === 'processing') {
        console.log(`🔄 Auto-idempotency: Waiting for duplicate request to complete`);
        
        // Poll cho đến khi có response hoặc timeout
        const result = await waitForResponse(fingerprint, 5000);
        if (result) {
          return res.status(result.statusCode).json(result.response);
        }
      }
      
      // Nếu đã có response, trả về luôn
      if (existingRequest.status === 'completed') {
        console.log(`🔄 Auto-idempotency: Returning cached response for duplicate request`);
        return res.status(existingRequest.statusCode).json(existingRequest.response);
      }
    }
    
    // Tạo key mới và đánh dấu đang xử lý
    idempotencyKey = uuidv4();
    isAutoGenerated = true;
    
    // Lưu fingerprint với trạng thái processing
    idempotencyStore.set(fingerprint, {
      status: 'processing',
      idempotencyKey,
      timestamp: Date.now()
    });
    
    // Gán key vào header để sử dụng sau
    req.headers['idempotency-key'] = idempotencyKey;
    req.idempotencyKey = idempotencyKey;
    req.isAutoGeneratedKey = true;
    req.requestFingerprint = fingerprint;
  } else {
    // Client gửi key thủ công
    const cached = idempotencyStore.get(idempotencyKey);
    
    if (cached && cached.status === 'completed') {
      console.log(`🔄 Idempotency hit: ${idempotencyKey}`);
      return res.status(cached.statusCode).json(cached.response);
    }
    
    req.idempotencyKey = idempotencyKey;
    req.isAutoGeneratedKey = false;
  }

  // Lưu lại res.json để intercept response
  const originalJson = res.json.bind(res);
  res.json = function(data) {
    const responseData = {
      response: data,
      timestamp: Date.now(),
      statusCode: res.statusCode,
      status: 'completed',
      idempotencyKey: idempotencyKey
    };
    
    // Lưu cả key và fingerprint
    idempotencyStore.set(idempotencyKey, responseData);
    
    if (req.requestFingerprint) {
      idempotencyStore.set(req.requestFingerprint, responseData);
    }
    
    // Thêm header cho client biết
    res.setHeader('X-Idempotency-Key', idempotencyKey);
    if (isAutoGenerated) {
      res.setHeader('X-Idempotency-Auto-Generated', 'true');
    }
    
    // Tự động cleanup sau 1 giờ
    const cleanup = () => {
      idempotencyStore.delete(idempotencyKey);
      if (req.requestFingerprint) {
        idempotencyStore.delete(req.requestFingerprint);
      }
    };
    
    // Giữ response trong 1 giờ, sau đó xóa
    setTimeout(cleanup, 3600000);
    
    originalJson(data);
  };

  // Xử lý lỗi - nếu có lỗi, xóa trạng thái processing
  const originalNext = next;
  res.on('error', () => {
    if (req.requestFingerprint) {
      idempotencyStore.delete(req.requestFingerprint);
    }
    idempotencyStore.delete(idempotencyKey);
  });
  
  next();
};

// Hàm đợi response của request đang xử lý
async function waitForResponse(fingerprint, timeout) {
  const startTime = Date.now();
  
  while (Date.now() - startTime < timeout) {
    const cached = idempotencyStore.get(fingerprint);
    
    if (cached && cached.status === 'completed') {
      return cached;
    }
    
    // Đợi 100ms rồi thử lại
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  
  console.warn(`⚠️ Auto-idempotency timeout for fingerprint: ${fingerprint}`);
  return null;
}

// Helper để clean up store
const cleanupStore = () => {
  const now = Date.now();
  for (const [key, value] of idempotencyStore.entries()) {
    if (now - value.timestamp > 3600000) { // 1 giờ
      idempotencyStore.delete(key);
    }
  }
};

// Cleanup mỗi 10 phút
setInterval(cleanupStore, 600000);

module.exports = idempotencyMiddleware;